"""Add descripcion field to Pais

Revision ID: 4eb4a4d67e54
Revises: e8a32a8c1d4b
Create Date: 2025-05-09 15:46:29.983720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4eb4a4d67e54'
down_revision: Union[str, None] = 'e8a32a8c1d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paises', sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paises', 'descripcion')
    # ### end Alembic commands ###
